### ISSUE TITLE
Fatal error when select database data to include in the backup

### ISSUE THREAD

**Issue by developer58456** [watchfulli/XCloner-Wordpress#196]
WordPress: 5.9
xCloner: 4.2.163
PHP: 8.0.14

When I want to expand a database in the step "Generate backup / 2. Database options" I get following fatal error:

```
PHP Fatal error:  Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable|array, string given in C:\\xampp\\apps\\wordpress\\htdocs\\wp-content\\plugins\\xcloner-backup-and-restore\\vendor\\watchfulli\\xcloner-core\\src\\Xcloner_Database.php:331
Stack trace:
#0 C:\\xampp\\apps\\wordpress\\htdocs\\wp-content\\plugins\\xcloner-backup-and-restore\\vendor\\watchfulli\\xcloner-core\\src\\Xcloner_Database.php(331): sizeof('')
#1 C:\\xampp\\apps\\wordpress\\htdocs\\wp-content\\plugins\\xcloner-backup-and-restore\\vendor\\watchfulli\\xcloner-core\\src\\Xcloner_Api.php(642): watchfulli\\XClonerCore\\Xcloner_Database->list_tables('bitnami_wordpre...', '', 1)
#2 C:\\xampp\\apps\\wordpress\\htdocs\\wp-includes\\class-wp-hook.php(307): watchfulli\\XClonerCore\\Xcloner_Api->get_database_tables_action('')
#3 C:\\xampp\\apps\\wordpress\\htdocs\\wp-includes\\class-wp-hook.php(331): WP_Hook->apply_filters('', Array)
#4 C:\\xampp\\apps\\wordpress\\htdocs\\wp-includes\\plugin.php(474): WP_Hook->do_action(Array)
#5 C:\\xampp\\apps\\wordpress\\htdocs\\wp-admin\\admin-ajax.php(187): do_action('wp_ajax_get_dat...')
#6 {main}
  thrown in C:\\xampp\\apps\\wordpress\\htdocs\\wp-content\\plugins\\xcloner-backup-and-restore\\vendor\\watchfulli\\xcloner-core\\src\\Xcloner_Database.php on line 331, referer: http://localhost/wordpress/wp-admin/admin.php?page=xcloner_generate_backups_page
```

Changing the line 642 in "Xcloner_Api.php" from
```
                $return = $this->xcloner_database->list_tables($database, "", 1);
```
to 
```
                $return = $this->xcloner_database->list_tables($database, array(), 1);
```
fixes the issue.

But it seems that the same call is also included in the "vendor_build.txt" file which I can't patch easily.

**Comment by vdrover** [comment]
Please test with the latest version and re-open this issue if this is still occurring.
