### ISSUE TITLE
BackWPup – conflicting with Backblaze storage save

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#235]
If you have this plugin installed on the website: BackWPup – WordPress Backup Plugin ( https://wordpress.org/plugins/backwpup/ ) when you try to setup Backblaze storage, it throws a critical error

I've reproduced and also a customer reported it

`#0 /home/*******/public_html/wp-content/plugins/backwpup/vendor/guzzlehttp/guzzle/src/HandlerStack.php(42): GuzzleHttp\choose_handler()
#1 /home/*******/public_html/wp-content/plugins/backwpup/vendor/guzzlehttp/guzzle/src/Client.php(65): GuzzleHttp\HandlerStack::create()`

**Comment by Ars92** [comment]
This issue is due to the fact that both XCloner and BackWPup are using different versions of Backblaze libraries.
To fix that, we should use different namespaces for vendor libraries. 
[mozart](https://github.com/coenjacobs/mozart)  or [php-scoper](https://github.com/humbug/php-scoper) should be integrated in our deploy script to solve this issue.

**Comment by jimiero** [comment]
@la-refactory just tested and it seems fine now
