### ISSUE TITLE
Error while executing a backup from site admin area

### ISSUE THREAD

**Issue by jimiero** [watchfulli/XCloner-Wordpress#266]
When trying to execute a backup it gets interrupted by this error:

`[2022-10-28 06:34:19] php_system.ERROR: E_ERROR: array ( 'type' => 1, 'message' => 'Uncaught RuntimeException: SplFileInfo::getType(): Lstat failed for wp-content/backups-d920O//.xcloner/index.html in /wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Local.php:509 Stack trace: #0 wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Local.php(509): SplFileInfo->getType() #1 /wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Local.php(452): League\\Flysystem\\Adapter\\Local->mapFileInfo(Object(SplFileInfo)) #2 /wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Local.php(305): League\\Flysystem\\Adapter\\Local->normalizeFileInfo(Object(SplFileInfo)) #3 /wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Filesystem.ph', 'file' => '/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem/src/Adapter/Local.php', 'line' => 509, ) [] []`

=====

Trying to uninstall and install the plugin back does not solves the issue.

We have credentials for a website where such error happens, was not able to reproduce on a test site.

**Comment by jimiero** [comment]
the customer confirmed with hosting there’s no restrictions on open_basedir

https://tabright.co.uk/_phpinfo_.php
