### ISSUE TITLE
SFTP connection error

### ISSUE THREAD

**Issue by bcsanford** [watchfulli/XCloner-Wordpress#45]
SFTP Fails to connect

Also it is not possible to delete/remove settings from the remote storage section, i ended up having to purge them from within mysql.

i tried both with password as well as with RSA Key got same error both ways 
`SFTP connection error: Could not login with username: myuser, host: my.domain.org`

```
[2020-03-03 02:19:09] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 02:23:46] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 02:41:09] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:41:09] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:41:24] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:41:24] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:42:51] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 02:44:24] xcloner_api.INFO: Processing ajax request ID _2dl1buf4x [] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Starting the filesystem scanner on root folder /www/SiteWP [] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding index.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding license.txt from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding nginx.conf from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding readme.html from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-activate.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-admin from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-blog-header.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-comments-post.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-config-sample.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-config.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-content from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-cron.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-includes from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-links-opml.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-load.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-login.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-mail.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-settings.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-signup.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding wp-trackback.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_file_system.INFO: Excluding xmlrpc.php from the filesystem list, matching pattern / ["FILESYSTEM SCAN","EXCLUDE"] []
[2020-03-03 02:44:24] xcloner_api.INFO: Processing ajax request ID _wkkeoeltm [] []
[2020-03-03 02:44:24] xcloner_database.INFO: Preparing the database recursion file [""] []
[2020-03-03 02:44:24] xcloner_api.INFO: Processing ajax request ID _si3ycoy7r [] []
[2020-03-03 02:44:24] xcloner_database.INFO: Starting new backup dump to file database-backup.sql [""] []
[2020-03-03 02:44:24] xcloner_database.INFO: Writing WP_SiteWP database dump headers [""] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_commentmeta table [""] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping 0 records starting position 0 from WP_SiteWP.wp_commentmeta table [""] []
[2020-03-03 02:44:24] xcloner_api.INFO: Processing ajax request ID _emjrq4sdi [] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_comments table [""] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping 1 records starting position 0 from WP_SiteWP.wp_comments table [""] []
[2020-03-03 02:44:24] xcloner_api.INFO: Processing ajax request ID _pwuzto44j [] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_links table [""] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping 0 records starting position 0 from WP_SiteWP.wp_links table [""] []
[2020-03-03 02:44:24] xcloner_api.INFO: Processing ajax request ID _w9nzhx6tf [] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_options table [""] []
[2020-03-03 02:44:24] xcloner_database.INFO: Dumping 333 records starting position 0 from WP_SiteWP.wp_options table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _5kptw1rkj [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_postmeta table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 492 records starting position 0 from WP_SiteWP.wp_postmeta table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _mr7yct7rn [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_posts table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 173 records starting position 0 from WP_SiteWP.wp_posts table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _506sild5m [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_term_relationships table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 18 records starting position 0 from WP_SiteWP.wp_term_relationships table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _s4n5gthqa [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_term_taxonomy table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 3 records starting position 0 from WP_SiteWP.wp_term_taxonomy table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _qhnjg9dtr [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_termmeta table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 0 records starting position 0 from WP_SiteWP.wp_termmeta table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _nxhmu5u8l [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_terms table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 3 records starting position 0 from WP_SiteWP.wp_terms table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _nyn2oz6ia [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_usermeta table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 49 records starting position 0 from WP_SiteWP.wp_usermeta table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _511wvm9zc [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_users table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 2 records starting position 0 from WP_SiteWP.wp_users table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _ots5iek3i [] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping the structure for WP_SiteWP.wp_xcloner_scheduler table [""] []
[2020-03-03 02:44:25] xcloner_database.INFO: Dumping 0 records starting position 0 from WP_SiteWP.wp_xcloner_scheduler table [""] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _y6vgofp7v [] []
[2020-03-03 02:44:25] xcloner_api.INFO: Processing ajax request ID _uyfcih5yp [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Initializing the backup archive backup_SiteWP.domain.com-2020-03-03_02-44-sql [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Adding 0 bytes of file xcloner-32d64/index.html to archive backup_SiteWP.domain.com-2020-03-03_02-44-sql-32d64.tar  [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Adding 316 bytes of file xcloner-32d64/backup_files.csv to archive backup_SiteWP.domain.com-2020-03-03_02-44-sql-32d64.tar  [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Adding 9297 bytes of file xcloner-32d64/xcloner-32d64.log to archive backup_SiteWP.domain.com-2020-03-03_02-44-sql-32d64.tar  [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Adding 647755 bytes of file xcloner-32d64/database-backup.sql to archive backup_SiteWP.domain.com-2020-03-03_02-44-sql-32d64.tar  [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Closing the backup archive backup_SiteWP.domain.com-2020-03-03_02-44-sql-32d64.tar with 2*512 zero bytes blocks. [] []
[2020-03-03 02:44:25] xcloner_archive.INFO: Sending backup notification to My.Email@gmail.com [] []
[2020-03-03 02:44:35] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 02:45:00] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:45:00] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:46:25] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:46:25] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:48:02] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:48:02] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:49:21] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:49:21] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:51:22] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:51:22] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:54:08] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 02:56:16] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:56:16] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:56:16] php_system.ERROR: E_ERROR: array (   'type' => 1,   'message' => 'Uncaught Error: Call to a member function setKey() on null in /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php:1375 Stack trace: #0 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(1569): phpseclib\\Crypt\\RSA->_parseKey(Array, \'ssh-rsa\') #1 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(278): phpseclib\\Crypt\\RSA->loadKey(\'ssh-rsa\') #2 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(255): League\\Flysystem\\Sftp\\SftpAdapter->getPrivateKey() #3 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(203): League\\Flysystem\\Sftp\\SftpAdapter->getAuthentication() #4 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(178): League\\Flysystem\\Sftp\\SftpAdapter',   'file' => '/www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php',   'line' => 1375, ) [] []
[2020-03-03 02:56:29] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 02:56:29] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 02:56:29] php_system.ERROR: E_ERROR: array (   'type' => 1,   'message' => 'Uncaught Error: Call to a member function setKey() on null in /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php:1375 Stack trace: #0 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php(1569): phpseclib\\Crypt\\RSA->_parseKey(Array, \'ssh-rsa\') #1 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(278): phpseclib\\Crypt\\RSA->loadKey(\'ssh-rsa\') #2 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(255): League\\Flysystem\\Sftp\\SftpAdapter->getPrivateKey() #3 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(203): League\\Flysystem\\Sftp\\SftpAdapter->getAuthentication() #4 /www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/league/flysystem-sftp/src/SftpAdapter.php(178): League\\Flysystem\\Sftp\\SftpAdapter',   'file' => '/www/SiteWP/wp-content/plugins/xcloner-backup-and-restore/vendor/phpseclib/phpseclib/phpseclib/Crypt/RSA.php',   'line' => 1375, ) [] []
[2020-03-03 03:01:53] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 03:11:12] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 03:15:43] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 03:16:15] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 03:16:38] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []
[2020-03-03 03:24:27] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 03:24:27] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 03:25:30] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 03:25:30] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 03:26:43] xcloner_remote_storage.INFO: Checking validity of the remote storage SFTP filesystem [] []
[2020-03-03 03:26:43] xcloner_remote_storage.INFO: Creating the SFTP remote storage connection [""] []
[2020-03-03 03:27:39] xcloner_file_system.INFO: Cleaning the backup storage on matching rules [] []

```

**Comment by vdrover** [comment]
I just cleared the fields and `saved` and the settings were gone. If this is this still an issue, please re-open as needed.
